name: Update Output File

on:
  schedule:
    # These are UTC times corresponding to UK time (BST or GMT).
    - cron: "0 8 * * *" # 9:00 AM UK
    - cron: "30 14 * * *" # 3:30 PM UK
    - cron: "0 19 * * *" # 8:00 PM UK
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: python ApiCall.py # Replace with the actual script name

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.json
          git commit -m "Auto-update output.json" || echo "No changes to commit"
          git push
